#
# OrangeFox Recovery build variables for qqcandy (OnePlus Ace Race / mt6895)
#

FOX_VARIANT := c15
OF_MAINTAINER := Furruka
FOX_BUILD_TYPE := Unofficial

FOX_VENDOR_BOOT_RECOVERY := 1
FOX_VIRTUAL_AB_DEVICE := 1
OF_NO_REFLASH_CURRENT_ORANGEFOX := 1

FOX_RECOVERY_SYSTEM_PARTITION := /dev/block/mapper/system
FOX_RECOVERY_VENDOR_PARTITION := /dev/block/mapper/vendor

FOX_ENABLE_APP_MANAGER := 1
FOX_INSTALLER_DISABLE_AUTOREBOOT := 0
FOX_DELETE_AROMAFM := 1
OF_FLASHLIGHT_ENABLE := 0

FOX_USE_BASH_SHELL := 1
FOX_ASH_IS_BASH := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_LZ4_BINARY := 1
FOX_USE_SED_BINARY := 1
FOX_USE_XZ_UTILS := 1
FOX_USE_ZSTD_BINARY := 1
FOX_USE_NANO_EDITOR := 1
FOX_USE_UPDATED_MAGISKBOOT := 1
FOX_USE_DATE_BINARY := 1

FOX_TARGET_DEVICES := qqcandy
TARGET_DEVICE_ALT := qqcandy
